apiVersion: v1
kind: Pod
metadata:
  name: my-app-portal-x
  labels:
    a1: superstar
    b2: jailer
    c3: padaiyappa
    app: ecom-portal
    tier: frontend
    mode: development
    version: 0.0.1-snapshot
spec:
  containers:
  - name: my-app-portal
    image: pokran75/my-angular-app
    ports:
    - containerPort: 9090