apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 6
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: my-app-portal
      labels:
        tier: frontend
        a1: superstar
        b2: jailer
        c3: padaiyappa
        app: ecom-portal
        mode: development
        version: 0.0.1-snapshot
    spec:
      containers:
        - name: my-app-portal
          image: pokran75/my-angular-app:1.0
          ports: 
          - containerPort: 80
