spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/ctol
    username: root
    password: root
logging:
  level:
    org.springframework.data.r2dbc: Debug
---
spring:
  profiles: test
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/ctol
    username: root
    password: root